version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: clproject
      PGDATA: /var/lib/db
    volumes:
      - data-volume:/var/lib/db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  flyway:
    entrypoint: ./scripts/migrate.sh
    image: boxfuse/flyway
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./database-schema/sql:/flyway/sql
      - ./dev/conf:/flyway/conf
      - ./dev/scripts:/flyway/scripts

  web:
    build: .
    image: web:latest
    volumes:
      - .:/data/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

volumes:
  data-volume: